### ISSUE TITLE
关于双人模式和一些其它更新

### ISSUE THREAD

**Issue by quadpixels** [bubububaoshe/bubububaoshe.github.io#4]
bubububaoshe你好呀
今天突然才看到你可能不用微博了的消息…不知之后该如何联络呢？
我先把我这边的更新情况说一下罢：
大致就是将客户端和服务端分开了，做成了静态页面即使布署在不同的地方也能连接到服务器的方式，然后加了一些和多人有关的提示（比如请等对方选完特殊牌之类的），然后还在抓一些残留的bug… 昨天突然发现在手机浏览器上还有一点问题，所以我还在看是什么问题。
嗯就先这样！

更新：那个一出现组合就卡住的问题似乎是在播音频时导致页面上所有的timeout都停止了，所以才会画面停住，并且Websocket也因为不再发心跳包而掉线的。似乎用promise的then()方法代替掉oneTimeFunction就可以了··而且有趣的是，这个问题只在手机版chrome内核的浏览器（包括Opera、Chrome和一些内置浏览器）才出现，移动版的Firefox、以及桌面版的Chrome/Firefox都不受其影响…  O_O

更新想做的功能 02-12 …
・断线重连
・从快照回放

**Comment by bubububaoshe** [comment]
我之前的audio播放是等音频播放结束再执行下一步，但手机端经常会有audio加载时间过长而被浏览器中断的情况，结果就是音频既不end也没error，下一步就没法执行了。所以后来我改了这部分，预读了每个audio的播放时长（存在combo_list里），程序在播放时长结束后就执行下一步（不管音频有没有成功播放），这样至少程序不会卡住了。我建议你先跟我的最后一版主程序merge一下再继续，因为我最后一版算是比较稳定bug比较少的，这样你就不用在我的旧版的缺陷上耗费时间了。

昂我之前一生气把微博卸载了，不过想一想确实我们就不好沟通了哈哈哈，所以我又装回来啦！在这个项目完结之前我会继续用它的 :3
