### ISSUE TITLE
Server return null with default settings in battle mode confirm stage

### ISSUE THREAD

**Issue by Aicitel** [bubububaoshe/bubububaoshe.github.io#7]
重现步骤
浏览器 chrome 75.0.3770.100-32bit
选择 1+2代人物 & 完成组合时播放语音
选择 连线->随机->确认
console log: [后手选取特殊牌], pack=null

代码版本为本仓库下versus分支 commit e6683ad70593288dcf5252e2858f4fa9806ebdd3

(P.S. 请问目前还有需要开发的新feature吗 以及如何参与contribute? ）

**Comment by quadpixels** [comment]
啊！我发现了，确实有这个bug，但是我传到服务器上的版本有一个修复之处还没有push到代码库里：
`if (pack == null) pack = [1, 2];`
现在push了
参与的话我觉得直接fork一个分支就行？不过现在有master和versus两个分支是因为之前一直是master先增加新功能（比如3代牌组）或者修复一些bug然后再并进versus中的。
功能的话…现在还没有统计任何数据，也许可以加上？

**Comment by Aicitel** [comment]
> 啊！我发现了，确实有这个bug，但是我传到服务器上的版本有一个修复之处还没有push到代码库里：
> `if (pack == null) pack = [1, 2];`
> 现在push了
> 参与的话我觉得直接fork一个分支就行？不过现在有master和versus两个分支是因为之前一直是master先增加新功能（比如3代牌组）或者修复一些bug然后再并进versus中的。
> 功能的话…现在还没有统计任何数据，也许可以加上？

所以之后的更新主要会在versus上进行对吗?
能够描述一下统计数据这个feature的细节吗，我个人希望能够加进去battle时聊天的功能（既然已经基于socket了聊天算是个easy fruit了），以及弄一个变量map到游戏元素的术语字典，可能我接触这方面比较少现在的结构和代码量撸的时候有些变量不是很能望文生义....
移动端apply browser fullscreen的改动应该也是easy fruit我也想添加一下。
BTW现在server端代码有上传到GitHub上吗，以及选用socketio而不是ws有什么特殊的考量吗？
Thanks a lot for your patience :D

**Comment by quadpixels** [comment]
我目前只动Versus，master主要是由原作者在改的
之前说的统计就是一局的回放，谁在每一步得了多少分之类，在最后列出来…相比之下确实是聊天的功能更有用！
移动端的话除了网页版，其实也可以直接用Phonegap打包成APK的。
术语在note.txt中记载了一部分，不知还有其它不清楚的么？
服务端就是index.js这个文件，用Socket.IO没有什么考量，因为我当时只知道这一个（看完了聊天室的Demo之后觉得可行就开始弄了），不太懂其它的方法…

**Comment by Aicitel** [comment]
websocket相比之下对于client的调试会更友好一些，但是相对的node侧的轮子没socketio多（我也很久没接触这方面的技术了可能了解有些过时），同时IOS侧的浏览器体验上websocket会有更好的扩展性，phonegap build起的安装包体积让我略微有点惊讶 ，感觉上15M的大小应该就已经足够了。打包时的node_modules似乎可以去掉一些内容，或是通过build脚本进行混淆压缩？以及对apk解压后有一些令人疑惑的递归目录包含了重复的assets，我会对此进行一些deep dive看看是不是可以减少压缩包的体积。
不清楚的部分主要是obtain这个操作，似乎这一个操作中可能引发很多的业务逻辑，包括刷新卡池&switch手牌与卡池的牌（这两个操作我都没有找到对应的术语...汗），这三个操作对于C/S的交互而言是区分给出response的还是统一由server端给出response?（噗这个问题我也会迅速翻阅一下server端代码）
十分惭愧尽管说着想要contribute但是仍然有许多问题不甚了解....请问开发组有其他IM的联络方式吗？
再次感谢!

**Comment by quadpixels** [comment]
确是，我发现了，我打包的时候有个重复的"root@"文件夹… 把它删掉后APK的大小就能减半… 这个root@的出现可能和我分区格式是btrfs有点关系吧，反正还时不时出过别的问题…

obtain操作在note.txt的第404行开始有些描述，确实是会引发其它操作的（比如刷新卡池就是dealOne，交换则是selectSwap，除此之外还有selectCopy、selectBan），服务器不保存游戏状态，只将一方的操作转发给另一方，另一方接收到后将对方的行动用对于电脑玩家同样方式进行处理就好了…

我们之前就只在微博上发私信这样…没有用过其它的IM联系方式，XD

**Comment by Aicitel** [comment]
这样的话刷新卡池与计算下一张进入卡池的牌等随机操作都由c端执行并提交操作结果(更新后的卡池手牌与牌库)，服务器对局内玩家(考虑扩展更多人参与的对局)进行广播而本身完全无状态，是为了减少服务器的载荷吗？这样的做法可能会略略有一些不那么传统。
另，服务器端ssl的支持我会想办法添加一下，这样或许能够规避很多浏览器安全性的问题。
(我在微博私信你了，但是我用不来微博几次发私信似乎都不成功…如果能够看到的话我就用微博向你请教了XD)

**Comment by quadpixels** [comment]
那样只是为了编写起来比较容易… 因为master分支的代码将DOM的操作与游戏逻辑写在了一起（比如controller.js），那些操作在NodeJS服务器上执行不了，只广播操作是最简单的方式。

是在一些Transactional Memory中看到这种只广播消息的做法的…

看到了一条消息，回复过去了，如果是你的话应该能看到的吧？
